export enum TokenTypes {
    REFRESH = 'REFRESH',
    FORGOT_PASSWORD = 'FORGOT_PASSWORD',
    ACCOUNT_VERIFY = 'ACCOUNT_VERIFY',
    ACCESS = 'ACCESS',
}

export enum TicketStatuses {
    DECLINED = 'DECLINED',
    APPROVED = 'APPROVED',
    PENDING = 'PENDING',
    CANCELED = 'CANCELED',
    APPROVED_CANCELED = 'APPROVED_CANCELED',
}

export enum TicketOfferStatuses {
    NO_OFFER = 'NO_OFFER',
    PENDING = 'PENDING',
    APPROVED = 'APPROVED',
    REJECTED = 'REJECTED',
}

export enum UserRoles {
    MEMBER = 'MEMBER',
    CLUB = 'CLUB',
    ADMIN = 'ADMIN'
}

export enum HttpStatusMessages {
    OK = 'OK',
    CREATED = 'CREATED',
    BAD_REQUEST = 'BAD_REQUEST',
    UNKNOWN = 'UNKNOWN',
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    UNAUTHORIZED = 'UNAUTHORIZED',
    FORBIDDEN = 'FORBIDDEN',
    NOT_FOUND = 'NOT_FOUND',
    NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
}

export enum ErrorMessages {
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    PASSWORD_NOT_MATCHED = 'PASSWORD_NOT_MATCHED',
    ALREADY_EXIST = 'ALREADY_EXIST',
    NUMBER_EXIST = 'NUMBER_EXIST',
    CLUB_ID_REQUIRED = 'CLUB_ID_REQUIRED',
    CLUB_EXIST = 'CLUB_EXIST',
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    CLUB_NOT_FOUND = 'CLUB_NOT_FOUND',
    QUESTION_NOT_FOUND = 'QUESTION_NOT_FOUND',
    MEMBER_NOT_FOUND = 'MEMBER_NOT_FOUND',
    COURSE_NOT_FOUND = 'COURSE_NOT_FOUND',
    TICKET_NOT_FOUND = 'TICKET_NOT_FOUND',
    FORBIDDEN = 'FORBIDDEN',
    INVALID_TOKEN = 'INVALID_TOKEN',
    INVALID_STATUS = 'INVALID_STATUS',
    INVALID_TICKET = 'INVALID_TICKET',
    TOKEN_PARSE_ERROR = 'TOKEN_PARSE_ERROR',
    USER_IS_NOT_ACTIVE = 'USER_IS_NOT_ACTIVE',
    USER_IS_NOT_VERIFIED = 'USER_IS_NOT_VERIFIED',
    MISSING_AUTHORIZATION = 'MISSING_AUTHORIZATION',
    INVALID_AUTHORIZATION_TYPE = 'INVALID_AUTHORIZATION_TYPE',
}

export enum HttpStatus {
    CONTINUE = 100,
    SWITCHING_PROTOCOLS = 101,
    PROCESSING = 102,
    EARLYHINTS = 103,
    OK = 200,
    CREATED = 201,
    ACCEPTED = 202,
    NON_AUTHORITATIVE_INFORMATION = 203,
    NO_CONTENT = 204,
    RESET_CONTENT = 205,
    PARTIAL_CONTENT = 206,
    AMBIGUOUS = 300,
    MOVED_PERMANENTLY = 301,
    FOUND = 302,
    SEE_OTHER = 303,
    NOT_MODIFIED = 304,
    TEMPORARY_REDIRECT = 307,
    PERMANENT_REDIRECT = 308,
    BAD_REQUEST = 400,
    UNAUTHORIZED = 401,
    PAYMENT_REQUIRED = 402,
    FORBIDDEN = 403,
    NOT_FOUND = 404,
    METHOD_NOT_ALLOWED = 405,
    NOT_ACCEPTABLE = 406,
    PROXY_AUTHENTICATION_REQUIRED = 407,
    REQUEST_TIMEOUT = 408,
    CONFLICT = 409,
    GONE = 410,
    LENGTH_REQUIRED = 411,
    PRECONDITION_FAILED = 412,
    PAYLOAD_TOO_LARGE = 413,
    URI_TOO_LONG = 414,
    UNSUPPORTED_MEDIA_TYPE = 415,
    REQUESTED_RANGE_NOT_SATISFIABLE = 416,
    EXPECTATION_FAILED = 417,
    I_AM_A_TEAPOT = 418,
    MISDIRECTED = 421,
    UNPROCESSABLE_ENTITY = 422,
    FAILED_DEPENDENCY = 424,
    PRECONDITION_REQUIRED = 428,
    TOO_MANY_REQUESTS = 429,
    INTERNAL_SERVER_ERROR = 500,
    NOT_IMPLEMENTED = 501,
    BAD_GATEWAY = 502,
    SERVICE_UNAVAILABLE = 503,
    GATEWAY_TIMEOUT = 504,
    HTTP_VERSION_NOT_SUPPORTED = 505
}
